listen_addresses = '*'
shared_buffers = 1GB
effective_cache_size = 3GB
work_mem = 16MB
max_connections = 200
wal_level = replica
archive_mode = on
archive_command = 'pgbackrest --stanza=ecomm archive-push %p'
max_wal_senders = 5
wal_keep_size = 1GB
shared_preload_libraries = 'pg_stat_statements'
log_min_duration_statement = 250
